<?php

namespace App\Http\Requests\API;

use App\Models\RecomendacionCandidato;
use InfyOm\Generator\Request\APIRequest;

class CreateRecomendacionCandidatoAPIRequest extends APIRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return RecomendacionCandidato::$rules;
    }

    public function messages()
    {
        return RecomendacionCandidato::$messages; // TODO: Change the autogenerated stub
    }
}
