<?php

namespace App\Http\Requests\API;

use App\Models\Candidato;
use App\Models\Contact;
use App\Rules\NumeroDomicilio;
use App\Rules\Piso;
use InfyOm\Generator\Request\APIRequest;

class UpdateContactAPIRequest extends APIRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'domicilio.calle' => 'nullable|string',
            'domicilio.numero' => ['nullable',new NumeroDomicilio()],
            'domicilio.piso' => ['nullable',new Piso(),'max:3'],
            'domicilio.departamento' => 'nullable|string',
            'domicilio.block' => 'nullable|string',
            'domicilio.codigo_postal' => 'nullable|integer',
            'domicilio.idlocalidad' => 'nullable|integer',
            'domicilio.idprovincia' => 'nullable|integer',
            'celular' => 'required|string',
            'telefono' => 'string|nullable',
            'email' => 'nullable|email',
        ];
    }
    public function messages()
    {
        return [
            'celular.required' => 'Celular es un campo requerido',
            'celular.string' => 'Celular es un string',
            'fnacimiento.date' => 'Fecha Nacimiento debe ser una fecha valida',
            'telefono.string' => 'Telefono es un string',
            'email.email' => 'Email no tiene formato email "example@example.com"',
//            'domicilio.calle.required' => 'Calle es un campo requerido',
            'domicilio.calle.string' => 'Calle es un string',
//            'domicilio.numero.required' => 'Número es un campo requerido',
            'domicilio.numero.integer' => 'Número es un integer',
            'domicilio.piso.max' => 'El campo Piso no debe contener mas de 3 caracteres.',
            'domicilio.departamento.string' => 'Departamento es un string',
            'domicilio.block.string' => 'Block es un string',
//            'domicilio.codigo_postal.required' => 'Código postal es un campo requerido',
            'domicilio.codigo_postal.integer' => 'Código postal es un integer',
//            'domicilio.idlocalidad.required' => 'Localidad es un campo requerido',
            'domicilio.idlocalidad.integer' => 'Localidad es un integer',
//            'domicilio.idprovincia.required' => 'Provincia es un campo requerido',
            'domicilio.idprovincia.integer' => 'Provincia es un integer',
        ]; // TODO: Change the autogenerated stub
    }
}
